### ISSUE TITLE
Unknown column token

### ISSUE THREAD

**Issue by hojati** [AlfnRU/roundcube-password_recovery#1]
hi alexander,
first many thanks for you plugin, it is a great feature for roundcube.

as I tried to set it up, got below error in log and the plugin just not working,
can you help, I think there is something wrong with the table

`[26-Jan-2022 10:13:37 +0100]: <q46k4n82> DB Error: [1054] Unknown column 'token' in 'field list' (SQL Query: SELECT email_other as altemail,phone as phone,question as question,answer as answer, token, token_validity, token='' OR token_validity < NOW() as token_expired FROM recovery_pwd WHERE username='xyz@xyz.com') in /var/www/html/roundcubemail-1.5.2/program/lib/Roundcube/rcube_db.php on line 566 (GET /webmail/?_task=mail&_action=getunread&_page=1&_remote=1&_unlock=0&_=1643188415650)`

I have create a new table "recovery_pwd" in roundcube database and the initial columns (email_other, phone, question, answer) is created but I think there should be more column like token or username or may be I am wrong.
is there any SQL command needs to be executed ? I didn't find any

please help
thank you

**Comment by AlfnRU** [comment]
All data is stored in the postfix database, in the mailbox table. This is in the comments in the config.php file.
> // Database connection string and table name with user passwords
> $config['pr_db_dsn']      = 'mysql://_USER_:_PASSWORD_@localhost/postfix';
> $config['pr_users_table'] = 'mailbox';

The plugin checks for these fields and, if none exist, creates them automatically. This is also written in config.php

> // Array with names for ext_fields in 'pr_users_table': [name_for_plugin => name_in_db]
> // When using the postfix database 'mailbox' table, you must add two columns to this table: 'question' and 'answer'
> // If the plugin does not find the columns it needs in the database, they will be created automatically
>

**Comment by hojati** [comment]
sorry but in Directadmin there is no such a database ('postfix'), as I see there is only da_roundcube available

**Comment by AlfnRU** [comment]
DirectAdmin...
In config.php you need to do this:

> in 'pr_db_dsn' write **roundcube database connection string**
> in 'pr_users_table' write **the name of the users table**
> and in 'pr_use_password_plugin' write **true**

Plugin itself will create the desired fields in the users table.

**Comment by hojati** [comment]
still no success.

`[26-Jan-2022 13:52:36 +0100]: <qb0tmhb2> DB Error: [1054] Unknown column 'token' in 'field list' (SQL Query: SELECT email_other as altemail,phone as phone,question as question,answer as answer, token, token_validity, token='' OR token_validity < NOW() as token_expired FROM users WHERE username='xyz@xyz.com') in /var/www/html/roundcubemail-1.5.2/program/lib/Roundcube/rcube_db.php on line 566 (POST /webmail/?_task=mail&_action=refresh)`

it is looking for 'token' column which doesnt exist in users table. It seems that like other columns it should be created.

**Comment by AlfnRU** [comment]
A fixed this error. Download [password_recovery.php](https://github.com/AlfnRU/roundcube-password_recovery/blob/main/password_recovery.php) and place it in directory /ROUNDCUBE_DIR/plugins/password_recovery/

**Comment by hojati** [comment]
another error or more:

`[26-Jan-2022 15:15:34 +0100]: <g9v2gj6n> DB Error: [1054] Unknown column 'token_validity' in 'field list' (SQL Query: SELECT token_validity FROM users) in /var/www/html/roundcubemail-1.5.2/program/lib/Roundcube/rcube_db.php on line 566 (POST /webmail/?_task=mail&_action=refresh)`

`[26-Jan-2022 15:15:34 +0100]: <g9v2gj6n> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CHARACTER SET utf8 NOT NULL DEFAULT 2000-01-01 00:00:00' at line 1 (SQL Query: ALTER TABLE users ADD token_validity DATETIME CHARACTER SET utf8 NOT NULL DEFAULT 2000-01-01 00:00:00) in /var/www/html/roundcubemail-1.5.2/program/lib/Roundcube/rcube_db.php on line 566 (POST /webmail/?_task=mail&_action=refresh)`

**Comment by AlfnRU** [comment]
Sorry, a little wrong. Download the file again

**Comment by AlfnRU** [comment]
Something is not going on today))
Fixed, checked, works

**Comment by hojati** [comment]
yeah 👍  , but I cant make it, the password not changed. I tried several time, no log no error even in debug mode. Everything seems fine but doesn't work with new password
[26-Jan-2022 17:01:37 +0100]: <7flo9sr5> Save new password for 'xyz@zyx' (IP: xxx)

**Comment by AlfnRU** [comment]
Um... Does the password plugin work? can users change their passwords?
