### ISSUE TITLE
SMTP settings not respected

### ISSUE THREAD

**Issue by freibadschwimmer** [AlfnRU/roundcube-password_recovery#10]
The plugin always tries to send emails with the recovery code from a no-reply@my.domain.com address, but does not respect the address defined in $config['pr_default_smtp_user']

Steps to reproduce:

Defining the SMTP settings in 
$config['pr_default_smtp_server'] = 'tls://my.domain.com';
$config['pr_default_smtp_user']   = 'someuser@my.domain.com';
$config['pr_default_smtp_pass']   = 'SOMEUSER_PASSWORD';

Expected behaviour:
Email with confirmation code is sent from email address someuser@my.domain.com.

What actually happens:
password_recovery tries to send an email from the address no-reply@my.domain.com.

Workaround:
One can create an email address no-reply@my.domain.com and an email with confirmation code will be send.
However, it would be expected that the plugin respects the defined smtp user.

**Comment by AlfnRU** [comment]
So it was conceived.
"pr_default_smtp_user" is used only for authorization on the SMTP server.

The return address is generated in the get_email_from () function in the file ./lib/send.php
The function takes the domain name from the administrator address, and substitutes "no-reply" ahead.

`
function get_email_from($email) {
  $parts = explode('@',$email);
  return 'no-reply@'.$parts[1];
}
`

It's not a bug, it's a feature.  ;)

**Comment by AlfnRU** [comment]
For the return address, I added another parameter to config - "pr_replyto_email"
