### ISSUE TITLE
Add some feedback if password does not meet the defined complexity or length

### ISSUE THREAD

**Issue by freibadschwimmer** [AlfnRU/roundcube-password_recovery#11]
I noticed, that when attempting to reset the password, if the password is too short or doesn't meet the set complexity, nothing happens.
It would be good to provide some feedback or a message to the user why the password is not being set, so the user understands to increase length or complexity of the new password. Ideally this would even show the actually defined length/complexity settings.

My setup:
password_recovery 1.2
password 5.3
Roundcube 1.6.0

**Comment by AlfnRU** [comment]
the plugin comes as is.
will commit - I will add
