### ISSUE TITLE
Change password algorithm

### ISSUE THREAD

**Issue by Bbertatum** [AlfnRU/roundcube-password_recovery#3]
Would it be possible to change the password algorithm (and prefix) with a less dirty method than changing this :+1: 

                   // $save['password'] = crypt($newpassword, '$1$' . rcube_utils::random_bytes(9));
                    $save['password'] = crypt($newpassword, '$6$' . rcube_utils::random_bytes(16));

And this 

           $fields[] = "password = '" .  $props['password'] . "'";
           $fields[] = "mypasswordfield = '{SHA512-CRYPT}"  .  $props['password'] . "'";

How customize the "password" field properly ?

This because using this setting :
$config['pr_use_password_plugin'] = true;

With properly configured password_plugin with custom query, then nothing happened (no DB update and no debug message, maybe variable and field assign issue...)

Thanks

**Comment by AlfnRU** [comment]
If the password plugin is installed and configured, all password changes are written through it. 

Тo understand the problem add to line 288 in the file password_recovery.php this is:
`$this->debug($message);`
and set $ config ['pr _ debug'] = true

This will add output to the debug messages from the plugin password

**Comment by Bbertatum** [comment]
I just changed add debug info at line 288 and config  ['pr _ debug'] = true was already at true.

After a new test : 
- All went fine to password fix... but in the database nothings happen and we have no idea what's wrong or just what's going on.

This is why we switch the settings to false and go our own way making this work with db scheme, different algorithm and prefix.

All that we got in logs : 

```
==> /var/log/roundcubemail/console.log <==
[01-Feb-2022 14:58:40 +0000]: <a41a4nfn> Save new password: Array
(
    [token] => X9QdnsaW57jFwHwGk4dKIJmCjAFkCUDZ
    [username] => bertatum@nftest.org
    [a] => save
    [newpassword] => newpassword
    [newpassword_confirm] => newpassword
    [code] => 560271
)

[01-Feb-2022 14:58:40 +0000]: <a41a4nfn> Update user 'bertatum@nftest.org' props: Array
(
    [0] => token = '', token_validity = NOW() + '0 MINUTE'
)
```
any idea ?

Regards

**Comment by vitviggs** [comment]
Hi, can you write a newbie guide on how to configure this plugin? I am using a Postfix-Dovecot-Postfixadmin-Roundcube configuration, with Mariadb, and ARGON2I password encryption algorithm. Are we suppose to insert Postfix db credentials or Roundcube db? It keeps telling me user no found when trying to use it. Thanks

**Comment by Bbertatum** [comment]
This issue could be closed, as you said :
If the password plugin is installed and configured, all password changes are written through it.

This is what we done and achieve to make the plugin work properly. The problem is database (PostgreSQL) related.

As a sidenote : this is a bit confusing to "be free" to chose one method or another and finally be forced to use one of the two.
